use_frameworks!
target 'SimpleRestClient_Tests' do
  pod 'SimpleRestClient', :path => '../'
  
  pod 'PromiseKit'
  pod 'ObjectMapper'
  pod 'Alamofire'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end
end
